runtime: python37

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

libraries:
- name: asgiref
  version: latest
- name: Django
  version: latest
- name: django-crispy-forms
  version: latest
- name: gunicorn
  version: latest
- name: psycopg2-binary
  version: latest
- name: sqlparse
  version: latest
- name: tzdata
  version: latest
- name: whitenoise
  version: latest